### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by aitor0307** [DiUS/qlprint#4]
Hi!

I'm trying to check if it recognizes a Brother QL700 with `sudo ./build/qlprint -i` but I'm getting the following error:
`Unable to open 'dev/usb/lp0': No such file or directory`
I've tried looking for it with lpadmin but I'm only getting the URI as `DeviceURI usb://Brother/QL-700?serial=000M8Z112146`

Have you run in any similar issues?

Kind regards,

**Comment by dfear** [comment]
This project needs libUSB support. Device URLS susch as: `DeviceURI usb://Brother/QL-700?serial=000M8Z112146`, are generated by LibUSB.

**Comment by aitor0307** [comment]
Hi David,

thanks for your reply! I will try it.

regards,

Aitor
